version: "3"
services:
  neo4j:
    image: "neo4j:5.1.0-community"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_memory_pagecache_size: 2G
      NEO4J_dbms_memory_heap_max__size: 2G
  mifune:
    image: "ghcr.io/prodyna/capt-mifune:latest"
    ports:
      - "8080:8080"
    volumes:
      - "../../graph-sample/bom/:/upload/:z"
      - "../../graph-sample/bom/:/model/:z"
    environment:
      QUARKUS_PROFILE: "local"
      MIFUNE_ROOT_PATH_API: "http://localhost:8080"
      MIFUNE_ROOT_PATH_UI: "http://localhost:8080"
      QUARKUS_NEO4J_URI: "bolt://neo4j:7687"
