version: "3"
services:
  neo4j:
    image: neo4j:4.4.3-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_memory_pagecache_size: 2G
      NEO4J_dbms_memory_heap_max__size: 2G
  mifune:
    image: prodyna/capt-mifune:latest
    ports:
      - "8080:8080"
    volumes:
      - ../../server/server/src/test/resources/samples/bom/:/upload/:z
      - ../../server/server/src/test/resources/samples/bom/:/model/:z
    environment:
      QUARKUS_PROFILE: local
      QUARKUS_NEO4J_URI: bolt://neo4j:7687
      QUARKUS_LOG_LEVEL: INFO
